name: Rust

on:
  push:
    paths:
      - rust/**
      - .github/workflows/rust.yaml

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: ./rust/run-tests.sh
